# Generated by Django 3.1 on 2020-08-06 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200806_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Bid'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date_listed'], 'verbose_name': 'auction_listing'},
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='bids_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
